id: ADCD643BB
title: Brief Smoke Offering to the Great Lion of the World
type: translation
pechas:
- I911D9297
- IAE7ED931
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:45:37.636832
  last_modified_at: 2023-01-04 12:45:37.636839
  collections:
  - Karma Chakme Series
  - Works of Tibetan Masters
alignment_to_base:
  I911D9297/BC49: B136
  IAE7ED931/92B4: B136
